name: dawaatime
description: A medication reminder app for the Middle East.
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ^3.7.2

dependencies:
  firebase_auth: ^5.5.4
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  flutter_launcher_icons: ^0.14.3
  permission_handler: ^12.0.0+1
  android_intent_plus: ^5.3.0
  package_info_plus: ^8.3.0
  flutter_timezone: ^4.1.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
  assets:
    - assets/app_icon.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
