name: dawatime
description: A medication reminder app.
publish_to: "none"
version: 1.0.0+4

environment:
  sdk: ^3.7.2

dependencies:
  firebase_auth: ^5.5.4
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  flutter_launcher_icons: ^0.14.3
  permission_handler: ^12.0.0+1
  android_intent_plus: ^5.3.0
  package_info_plus: ^8.3.0
  flutter_timezone: ^4.1.1
  url_launcher: ^6.3.1
  background_fetch: ^1.3.8
  shared_preferences: ^2.5.3
  flutter_slidable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraBold.ttf
  assets:
    - assets/DawaTime.png
    - assets/DawaTime_green.png
    - assets/DawaTime_white.png
    - assets/notification_sound.wav
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/DawaTime.png"
  remove_alpha_ios: true
